server:
  port: 8130

spring:
  profiles:
    active: dev
  application:
    name: service-oss
  cloud:
    nacos:
      discovery:
        # nacos 服務地址
        server-addr: localhost:8848

aliyun:
  oss:
    # endpoint 無需添加 https:// 前綴，且無需 / 後綴，示例： oss-cn-hangzhou.aliyuncs.com
    endpoint: oss-cn-hangzhou.aliyuncs.com
    keyId:
    keySecret:
    bucketName:

