server:
  port: 8120

spring:
  profiles:
    active: dev
  application:
    name: service-sms
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: redson
    # 最大等待時長，超時則拋出異常，否則請求一直等待
    timeout: 3000ms
    lettuce:
      pool:
        # 最大連結數
        max-active: 30
        # 最大阻塞等待時間，默認 -1，負數表示沒有限制
        max-wait: -1
        # 最大空閒連結，默認 8
        max-idle: 8
        # 最小空閒連結，默認 8
        min-idle: 0

aliyun:
  sms:
    region-id: cn-hangzhou
    key-id:
    key-secret:
    template-code: SMS_154950909
    sign-name: 阿里云短信测试
